urls:
  api: "https://devnet-api.multiversx.com"
  swagger:
    - "http://localhost:3000"
    - "https://devnet-microservice.multiversx.com"
    - "https://testnet-microservice.multiversx.com"
    - "https://microservice.multiversx.com"
  redis: "127.0.0.1"
features:
  publicApi:
    enabled: true
    port: 3000
  privateApi:
    enabled: true
    port: 4000
  cacheWarmer:
    enabled: false
    port: 5201
  transactionProcessor:
    enabled: false
    port: 5202
    maxLookBehind: 100
  queueWorker:
    enabled: true
    port: 8000
  keepAliveAgent:
    enabled: true
nativeAuth:
  maxExpirySeconds:
  acceptedOrigins:
    - "utils.multiversx.com"
chatGpt:
  apiKey: "INSERT_GPT_SECRET_KEY_HERE"
security:
  admins:
rateLimiterSecret:
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
useCachingInterceptor: false
